[package]
authors = ["Euan Rochester <euan@rochester.me.uk>"]
name = "modpack_tool"
version = "0.1.0"

[dependencies]
clap = "2.24"
env_logger = "0.4"
error-chain = "0.11"
html5ever = "0.20.0"
hyper = "0.11.2"
hyper-tls = "0.1.2"
kuchiki = "0.6"
lazy_static = "0.2.9"
log = "*"
nom = {version = "3.2.1", features = ["regexp"]}
regex = "0.2.2"
selectors = "0.18.0"
serde = "*"
serde_derive = "*"
serde_json = "*"
sha1 = "*"
slog-json = "2"
slog-stdlog = "3"
slog-term = "2"
termcolor = "0.3.3"
time = "*"
tokio-core = "0.1"
url = "1.4"
zip = "0.2"

[dependencies.futures-await]
git = "https://github.com/alexcrichton/futures-await"

[dependencies.semver]
features = ["serde"]
version = "0.8.0"

[dependencies.slog]
features = ["max_level_trace"]
version = "2"
